# Generated by Django 5.2.14 on 2026-05-26 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_publicacao', models.DateField(auto_now_add=True, verbose_name='Data de publicação')),
                ('importante', models.BooleanField(default=False, verbose_name='Importante')),
            ],
            options={
                'verbose_name': 'Aviso',
                'verbose_name_plural': 'Avisos',
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do jogador')),
                ('posicao', models.CharField(max_length=50, verbose_name='Posição')),
                ('numero_camisa', models.IntegerField(blank=True, null=True, verbose_name='Número da camisa')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo no time')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adversario', models.CharField(max_length=100, verbose_name='Adversário')),
                ('data', models.DateField(verbose_name='Data da partida')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('local', models.CharField(max_length=200, verbose_name='Local')),
                ('tipo', models.CharField(choices=[('amistoso', 'Amistoso'), ('campeonato', 'Campeonato')], max_length=20, verbose_name='Tipo')),
                ('gols_pro', models.IntegerField(blank=True, null=True, verbose_name='Gols a favor')),
                ('gols_contra', models.IntegerField(blank=True, null=True, verbose_name='Gols contra')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do treino')),
                ('horario', models.TimeField(verbose_name='Horário')),
                ('local', models.CharField(max_length=200, verbose_name='Local')),
                ('descricao', models.CharField(blank=True, max_length=300, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Treino',
                'verbose_name_plural': 'Treinos',
            },
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.CharField(max_length=20, verbose_name='Mês de referência')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor (R$)')),
                ('status', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente'), ('atrasado', 'Atrasado')], max_length=20, verbose_name='Status')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogador', verbose_name='Jogador')),
            ],
            options={
                'verbose_name': 'Mensalidade',
                'verbose_name_plural': 'Mensalidades',
            },
        ),
        migrations.CreateModel(
            name='PresencaTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('justificado', 'Justificado')], max_length=20, verbose_name='Status')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogador', verbose_name='Jogador')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.treino', verbose_name='Treino')),
            ],
            options={
                'verbose_name': 'Presença em Treino',
                'verbose_name_plural': 'Presenças em Treinos',
            },
        ),
    ]
