# Generated by Django 5.2.14 on 2026-06-02 17:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('organizador', models.CharField(max_length=100)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ComissaoTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=50)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='aviso',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mensalidade',
            options={'verbose_name': 'Aviso', 'verbose_name_plural': 'Avisos'},
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='data_publicacao',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='importante',
        ),
        migrations.RemoveField(
            model_name='aviso',
            name='mensagem',
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='data_publicacao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de publicação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='importante',
            field=models.BooleanField(default=False, verbose_name='Importante'),
        ),
        migrations.AddField(
            model_name='mensalidade',
            name='mensagem',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Mensagem'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Escalacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titular', models.BooleanField(default=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.partida')),
            ],
        ),
        migrations.CreateModel(
            name='EstatisticaJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols', models.IntegerField(default=0)),
                ('assistencias', models.IntegerField(default=0)),
                ('cartoes_amarelos', models.IntegerField(default=0)),
                ('cartoes_vermelhos', models.IntegerField(default=0)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jogador')),
            ],
        ),
    ]
