# Generated by Django 5.2.14 on 2026-06-02 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_campeonato_comissaotecnica_eventocalendario_local_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aviso',
            options={'verbose_name': 'Aviso', 'verbose_name_plural': 'Avisos'},
        ),
        migrations.AlterModelOptions(
            name='mensalidade',
            options={'verbose_name': 'Mensalidade', 'verbose_name_plural': 'Mensalidades'},
        ),
        migrations.RemoveField(
            model_name='mensalidade',
            name='data_publicacao',
        ),
        migrations.RemoveField(
            model_name='mensalidade',
            name='importante',
        ),
        migrations.RemoveField(
            model_name='mensalidade',
            name='mensagem',
        ),
        migrations.AddField(
            model_name='aviso',
            name='data_publicacao',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de publicação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aviso',
            name='importante',
            field=models.BooleanField(default=False, verbose_name='Importante'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='mensagem',
            field=models.TextField(default='Sem mensagem', verbose_name='Mensagem'),
            preserve_default=False,
        ),
    ]
