# Generated by Django 5.2.14 on 2026-06-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_aviso_options_alter_mensalidade_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campeonato',
            options={'verbose_name': 'Campeonato', 'verbose_name_plural': 'Campeonatos'},
        ),
        migrations.AlterModelOptions(
            name='comissaotecnica',
            options={'verbose_name': 'Comissão Técnica', 'verbose_name_plural': 'Comissões Técnicas'},
        ),
        migrations.AlterModelOptions(
            name='escalacao',
            options={'verbose_name': 'Escalação', 'verbose_name_plural': 'Escalações'},
        ),
        migrations.AlterModelOptions(
            name='estatisticajogador',
            options={'verbose_name': 'Estatística de Jogador', 'verbose_name_plural': 'Estatísticas de Jogadores'},
        ),
        migrations.AlterModelOptions(
            name='eventocalendario',
            options={'verbose_name': 'Evento do Calendário', 'verbose_name_plural': 'Eventos do Calendário'},
        ),
        migrations.AlterModelOptions(
            name='local',
            options={'verbose_name': 'Local', 'verbose_name_plural': 'Locais'},
        ),
        migrations.AlterModelOptions(
            name='patrocinador',
            options={'verbose_name': 'Patrocinador', 'verbose_name_plural': 'Patrocinadores'},
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='patrocinadores/'),
        ),
    ]
